Name:           ros-melodic-rqt-pose-view
Version:        0.5.8
Release:        0%{?dist}
Summary:        ROS rqt_pose_view package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rqt_pose_view
Source0:        %{name}-%{version}.tar.gz

Requires:       PyOpenGL
Requires:       python-rospkg
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-gl-dependency
Requires:       ros-melodic-python-qt-binding >= 0.2.19
Requires:       ros-melodic-rospy
Requires:       ros-melodic-rostopic
Requires:       ros-melodic-rqt-gui
Requires:       ros-melodic-rqt-gui-py
Requires:       ros-melodic-rqt-py-common
Requires:       ros-melodic-tf
BuildRequires:  ros-melodic-catkin

%description
rqt_pose_view provides a GUI plugin for visualizing 3D poses.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Mar 22 2018 Dirk Thomas <dthomas@osrfoundation.org> - 0.5.8-0
- Autogenerated by Bloom

